### ISSUE TITLE
Segfault Ubuntu 18.04

### ISSUE THREAD

**Issue by tran5** [lbryio/cpuminer#2]
Hello,

After a clean git clone, autogen, make :
```
./minerd -a lbry -o stratum+tcp://127.0.0.1:3334/ -D -u bH347ZT2dt1f7GU3N5xjBzANtsCoKBA6oE -p x -t 1 -t 4 --stratum
[2020-05-08 16:36:40] 4 miner threads started, using 'lbry' algorithm.
[2020-05-08 16:36:40] Starting Stratum on stratum+tcp://127.0.0.1:3334/
[2020-05-08 16:36:40] Stratum session id: 1c4187c7413199ed4ee808032c853901
[2020-05-08 16:36:40] Stratum difficulty set to 1
Segmentation fault
```

Détails:

```
[2020-05-10 03:08:43] 4 miner threads started, using 'lbry' algorithm.
[2020-05-10 03:08:43] Binding thread 3 to cpu 3
[2020-05-10 03:08:43] Binding thread 1 to cpu 1
[2020-05-10 03:08:43] Binding thread 2 to cpu 2
[2020-05-10 03:08:44] Stratum session id: 3d155dbf3d162088120c6e06488a14d9
[2020-05-10 03:08:45] Stratum difficulty set to 512

Thread 3 "minerd" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff6225700 (LWP 8940)]
__strcmp_sse2 () at ../sysdeps/x86_64/strcmp.S:174
174	../sysdeps/x86_64/strcmp.S: No such file or directory.
(gdb) backtrace 
#0  __strcmp_sse2 () at ../sysdeps/x86_64/strcmp.S:174
#1  0x000055555555a1bd in stratum_thread (userdata=<optimized out>) at cpu-miner.c:1490
#2  stratum_thread (userdata=<optimized out>) at cpu-miner.c:1457
#3  0x00007ffff7f0afa3 in start_thread (arg=<optimized out>) at pthread_create.c:486
#4  0x00007ffff7e3b4cf in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

Seems like : 
```
if (stratum.job.job_id &&
```
could be more like:
```
if (stratum.job.job_id && g_work.job_id &&
```

**Comment by BrannonKing** [comment]
I just want to confirm that I have not used this cpuminer build with a stratum server. I have only used it with a local lbrycrd instance directly.
